version: 2.1

orbs:
  ruby: circleci/ruby@1.7.1

jobs:
  build:
    docker:
      - image: cimg/base
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Read ruby version"
          command: echo 'export RUBY_VERSION="$(cat .ruby-version)"' >> $BASH_ENV
      - run:
          name: "Sanity Check"
          command: printenv RUBY_VERSION
      - ruby/install:
          version: '${RUBY_VERSION}'
      - run:
          name: Check installed version
          command: |
            ruby --version
